CREATE TABLE Businesses (
  BusinessID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BusinessName VARCHAR(30) NOT NULL UNIQUE,
  OwnerName VARCHAR(30) NOT NULL UNIQUE,
  Address VARCHAR(30) NOT NULL,
  ContactNumber VARCHAR(10) NOT NULL UNIQUE,
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);