CREATE TABLE Businesses (
  BusinessID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BusinessName VARCHAR(30) NOT NULL,
  OwnerName VARCHAR(30) NOT NULL,
  Address VARCHAR(30) NOT NULL,
  ContactNumber VARCHAR(10) NOT NULL,
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);