CREATE TABLE CartItems (
  CartItemID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ProductID INT,
  FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE,
  Quantity INT NOT NULL,
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);