CREATE TABLE Orders (
  OrderID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  OrderDate DATETIME NOT NULL,
  TotalPrice INT(255) NOT NULL,
  StatusID INT,
  FOREIGN KEY (StatusID) REFERENCES Status(StatusID) ON DELETE CASCADE,
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);