CREATE TABLE Reviews (
  ReviewID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Rating INT(5) NOT NULL,
  Comment VARCHAR(255) NOT NULL,
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  ProductID INT,
  FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE
);