CREATE TABLE SupportTickets (
  TicketID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Description LONGTEXT NOT NULL,
  Subject VARCHAR(255) NOT NULL,
  StatusID INT,
  FOREIGN KEY (StatusID) REFERENCES Status(StatusID) ON DELETE CASCADE,
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);
