CREATE TABLE Users (
    UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(30) NOT NULL,
    Password VARCHAR(20) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    UserType VARCHAR(20) NOT NULL
);
